using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Geo_Quiz
{
    public partial class UC_Login : UserControl
    {
        private readonly string[] fileAccounts;
        private string newAccount;

        private string enteredUsername;
        private string enteredPassword;
        private string[] usernames = new string[0];
        private string[] passwords = new string[0];

        public static string filepath = Path.Combine(Directory.GetCurrentDirectory(), "..\\..\\", "Data");
        private readonly string fullpath;

        public UC_Login()
        {   
            InitializeComponent();

            L_Header.Text = F_SignIn.header;

            fullpath = Path.Combine(filepath, "Accounts.txt");
            fileAccounts = File.ReadAllLines(fullpath);

            SetUsernamesAndPasswords();
        }

        private void SetUsernamesAndPasswords()
        {
            Array.Resize(ref usernames, fileAccounts.Length);
            Array.Resize(ref passwords, fileAccounts.Length);

            int i = 0;
            foreach (string s in fileAccounts)
            {
                usernames[i] = s.Split('\t')[0];
                passwords[i] = s.Split('\t')[1];

                i++;
            }
        }

        private void B_Enter_Click(object sender, EventArgs e)
        {
            enteredUsername = TB_Username.Text;
            enteredPassword = TB_Password.Text;

            L_WrongPass.Visible = false;
            L_WrongUsername.Visible = false;

            switch (F_SignIn.type)
            {
                case "SignIn":
                    SignIn();
                    break;
                case "SignUp":
                    SignUp();
                    break;
            }
        }

        private void SignUp()
        {
            bool success = true;

            if (enteredUsername == null || enteredUsername == "" || enteredUsername.Length > 32)
            {
                success = false;
                L_WrongUsername.Visible = true; 
            }

            if (enteredPassword == null || enteredPassword == "" || enteredPassword.Length > 32)
            {
                success = false;
                L_WrongPass.Visible = true;
            }

            foreach (string s in usernames)
            {
                if (enteredUsername == s)
                {                    
                    L_WrongUsername.Visible = true;
                    TB_Username.Text = "";
                    TB_Password.Text = "";
                    success = false;
                }
            }
            
            if (success == true)
            {
                newAccount = enteredUsername + '\t' + HashPasswords(enteredPassword) + '\n';
                File.AppendAllText(fullpath, newAccount);

                SuccessfulLogIn(enteredUsername);
            }
        }

        private void SignIn()
        {
            bool success = false;
            
            for (int j = 0; j < usernames.Length; j++)
            {
                if (enteredUsername == usernames[j])
                {
                    success = true;
                    if (passwords[j] == HashPasswords(enteredPassword))
                    {
                        SuccessfulLogIn(usernames[j]);
                    }
                    else
                    {
                        L_WrongPass.Visible = true;
                        TB_Password.Text = "";
                    }                    
                }
            }

            if (success == false)
            {
                L_WrongUsername.Visible = true;
            }
        }

        private void SuccessfulLogIn(string setUsername)
        {
            F_SignIn.loggedIn = true;
            F_SignIn.loggedInAccount = setUsername;

                //generated by an AI (ChatGPT)
            F_SignIn form = ParentForm as F_SignIn;
            form.SetCurrentAccLabel();
                //end

            Dispose();
        }

            //copied tutorial from https://www.youtube.com/watch?v=IO4xdQVuRZQ
        private string HashPasswords(string password)
        {
            SHA256 sha256 = SHA256.Create();            
            byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));

            var sb = new StringBuilder();
            foreach (byte b in bytes)
            {
                sb.Append(b.ToString("x2"));
            }

            return sb.ToString();
        }
            //end
        
        private void B_Exit_Click(object sender, EventArgs e)
        {
            Dispose();            
        }
    }
}
